on:
  pull_request_target:
    types:
      - closed
jobs:
  if_merged:
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.title, '[SECURITY]')  
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo The PR was merged and is a security-patch